### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [Lunaxod/Ringostat-V4-GTM-tpl#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) encodeUri should be used on user provided url values that are used to create your url. These methods return an encoded Uniform Resource Identifier (URI) by escaping special characters. This method returns a string that represents the provided string encoded as a URI. You should use this method on transportUrl and projectHash when generating the url
const url = transportUrl + '/v4/' + projectHash + '.js';

**Comment by Lunaxod** [comment]
Fixed
